### ISSUE TITLE
Speedup maxlfq_solve function

### ISSUE THREAD

**Issue by baderd** [vdemichev/diann-rpackage#1]
Hi Vadim,

Just ran your R code examples to get gene and protein LFQ matrices from DiaNN 1.7.10 output. Looks really great so far! Amazing job! Thank you again!

I wonder whether you could speed up the `maxlfq_solve()` function?
https://github.com/vdemichev/diann-rpackage/blob/master/src/diann-rcpp.cpp#L17

We saw a very promising video of Max Strauss (https://github.com/straussmaximilian) from the Matthias Mann lab speaking about a manifold speed increase for the MaxLFQ algorithm using python machine learning libraries (see below, 20min).

Conference talk of Max Strauss about "AlphaPept":
https://www.youtube.com/watch?v=bMTNx_4nZlQ

I will sent him a link to this issue, so you can get in contact on an academic level and maybe push the proteomics open source front even further ;-)

Cheers,
Daniel

**Comment by vdemichev** [comment]
Hi Daniel! 

Yes, it's definitely possible to speed the MaxLFQ computation, for example by making it multi-threaded (each thread working on its own protein - this is how DIA-NN itself does it, but I haven't yet studied how to implement this in R). 

I think in the video he refers to the normalisation problem also described in the MaxLFQ paper, which is a different problem. With MaxLFQ protein quantification it is in theory a simpler algorithm. I use a direct method (Cholesky decomposition), for very large number of samples (greater than several thousand) it might make sense to also use an iterative method like conjugate gradient and stop it early (instead of doing ~N iterations where N is the number of samples). I might do some tests of this in the future.

Another solution is to just split the large dataset in batches and do MaxLFQ for each batch separately. Meaning that the workflow would be (filter peptides) -> (batch correct on peptide level) -> (MaxLFQ for each batch separately - very fast) -> (batch correct on protein level if batch effects still detected). This way an arbitrarily large dataset can be processed.

Best wishes,

Vadim
